# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 4.3

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/anshr/Projects/ChessEngine

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/anshr/Projects/ChessEngine

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target test
test:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running tests..."
	/usr/bin/ctest $(ARGS)
.PHONY : test

# Special rule for the target test
test/fast: test
.PHONY : test/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/anshr/Projects/ChessEngine/CMakeFiles /home/anshr/Projects/ChessEngine//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/anshr/Projects/ChessEngine/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named chess_engine_lib

# Build rule for target.
chess_engine_lib: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 chess_engine_lib
.PHONY : chess_engine_lib

# fast build rule for target.
chess_engine_lib/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/chess_engine_lib.dir/build.make CMakeFiles/chess_engine_lib.dir/build
.PHONY : chess_engine_lib/fast

#=============================================================================
# Target rules for targets named chess_engine

# Build rule for target.
chess_engine: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 chess_engine
.PHONY : chess_engine

# fast build rule for target.
chess_engine/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/chess_engine.dir/build.make CMakeFiles/chess_engine.dir/build
.PHONY : chess_engine/fast

#=============================================================================
# Target rules for targets named test_movegen

# Build rule for target.
test_movegen: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_movegen
.PHONY : test_movegen

# fast build rule for target.
test_movegen/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_movegen.dir/build.make CMakeFiles/test_movegen.dir/build
.PHONY : test_movegen/fast

src/Main/main.o: src/Main/main.cpp.o
.PHONY : src/Main/main.o

# target to build an object file
src/Main/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/chess_engine.dir/build.make CMakeFiles/chess_engine.dir/src/Main/main.cpp.o
.PHONY : src/Main/main.cpp.o

src/Main/main.i: src/Main/main.cpp.i
.PHONY : src/Main/main.i

# target to preprocess a source file
src/Main/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/chess_engine.dir/build.make CMakeFiles/chess_engine.dir/src/Main/main.cpp.i
.PHONY : src/Main/main.cpp.i

src/Main/main.s: src/Main/main.cpp.s
.PHONY : src/Main/main.s

# target to generate assembly for a file
src/Main/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/chess_engine.dir/build.make CMakeFiles/chess_engine.dir/src/Main/main.cpp.s
.PHONY : src/Main/main.cpp.s

src/board_manager/board_manager.o: src/board_manager/board_manager.cpp.o
.PHONY : src/board_manager/board_manager.o

# target to build an object file
src/board_manager/board_manager.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/chess_engine_lib.dir/build.make CMakeFiles/chess_engine_lib.dir/src/board_manager/board_manager.cpp.o
.PHONY : src/board_manager/board_manager.cpp.o

src/board_manager/board_manager.i: src/board_manager/board_manager.cpp.i
.PHONY : src/board_manager/board_manager.i

# target to preprocess a source file
src/board_manager/board_manager.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/chess_engine_lib.dir/build.make CMakeFiles/chess_engine_lib.dir/src/board_manager/board_manager.cpp.i
.PHONY : src/board_manager/board_manager.cpp.i

src/board_manager/board_manager.s: src/board_manager/board_manager.cpp.s
.PHONY : src/board_manager/board_manager.s

# target to generate assembly for a file
src/board_manager/board_manager.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/chess_engine_lib.dir/build.make CMakeFiles/chess_engine_lib.dir/src/board_manager/board_manager.cpp.s
.PHONY : src/board_manager/board_manager.cpp.s

src/evaluate/evaluate.o: src/evaluate/evaluate.cpp.o
.PHONY : src/evaluate/evaluate.o

# target to build an object file
src/evaluate/evaluate.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/chess_engine_lib.dir/build.make CMakeFiles/chess_engine_lib.dir/src/evaluate/evaluate.cpp.o
.PHONY : src/evaluate/evaluate.cpp.o

src/evaluate/evaluate.i: src/evaluate/evaluate.cpp.i
.PHONY : src/evaluate/evaluate.i

# target to preprocess a source file
src/evaluate/evaluate.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/chess_engine_lib.dir/build.make CMakeFiles/chess_engine_lib.dir/src/evaluate/evaluate.cpp.i
.PHONY : src/evaluate/evaluate.cpp.i

src/evaluate/evaluate.s: src/evaluate/evaluate.cpp.s
.PHONY : src/evaluate/evaluate.s

# target to generate assembly for a file
src/evaluate/evaluate.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/chess_engine_lib.dir/build.make CMakeFiles/chess_engine_lib.dir/src/evaluate/evaluate.cpp.s
.PHONY : src/evaluate/evaluate.cpp.s

src/lookup_tables/lookup_tables.o: src/lookup_tables/lookup_tables.cpp.o
.PHONY : src/lookup_tables/lookup_tables.o

# target to build an object file
src/lookup_tables/lookup_tables.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/chess_engine_lib.dir/build.make CMakeFiles/chess_engine_lib.dir/src/lookup_tables/lookup_tables.cpp.o
.PHONY : src/lookup_tables/lookup_tables.cpp.o

src/lookup_tables/lookup_tables.i: src/lookup_tables/lookup_tables.cpp.i
.PHONY : src/lookup_tables/lookup_tables.i

# target to preprocess a source file
src/lookup_tables/lookup_tables.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/chess_engine_lib.dir/build.make CMakeFiles/chess_engine_lib.dir/src/lookup_tables/lookup_tables.cpp.i
.PHONY : src/lookup_tables/lookup_tables.cpp.i

src/lookup_tables/lookup_tables.s: src/lookup_tables/lookup_tables.cpp.s
.PHONY : src/lookup_tables/lookup_tables.s

# target to generate assembly for a file
src/lookup_tables/lookup_tables.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/chess_engine_lib.dir/build.make CMakeFiles/chess_engine_lib.dir/src/lookup_tables/lookup_tables.cpp.s
.PHONY : src/lookup_tables/lookup_tables.cpp.s

src/search/search.o: src/search/search.cpp.o
.PHONY : src/search/search.o

# target to build an object file
src/search/search.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/chess_engine_lib.dir/build.make CMakeFiles/chess_engine_lib.dir/src/search/search.cpp.o
.PHONY : src/search/search.cpp.o

src/search/search.i: src/search/search.cpp.i
.PHONY : src/search/search.i

# target to preprocess a source file
src/search/search.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/chess_engine_lib.dir/build.make CMakeFiles/chess_engine_lib.dir/src/search/search.cpp.i
.PHONY : src/search/search.cpp.i

src/search/search.s: src/search/search.cpp.s
.PHONY : src/search/search.s

# target to generate assembly for a file
src/search/search.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/chess_engine_lib.dir/build.make CMakeFiles/chess_engine_lib.dir/src/search/search.cpp.s
.PHONY : src/search/search.cpp.s

tests/test_move_making.o: tests/test_move_making.cpp.o
.PHONY : tests/test_move_making.o

# target to build an object file
tests/test_move_making.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_movegen.dir/build.make CMakeFiles/test_movegen.dir/tests/test_move_making.cpp.o
.PHONY : tests/test_move_making.cpp.o

tests/test_move_making.i: tests/test_move_making.cpp.i
.PHONY : tests/test_move_making.i

# target to preprocess a source file
tests/test_move_making.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_movegen.dir/build.make CMakeFiles/test_movegen.dir/tests/test_move_making.cpp.i
.PHONY : tests/test_move_making.cpp.i

tests/test_move_making.s: tests/test_move_making.cpp.s
.PHONY : tests/test_move_making.s

# target to generate assembly for a file
tests/test_move_making.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_movegen.dir/build.make CMakeFiles/test_movegen.dir/tests/test_move_making.cpp.s
.PHONY : tests/test_move_making.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... test"
	@echo "... chess_engine"
	@echo "... chess_engine_lib"
	@echo "... test_movegen"
	@echo "... src/Main/main.o"
	@echo "... src/Main/main.i"
	@echo "... src/Main/main.s"
	@echo "... src/board_manager/board_manager.o"
	@echo "... src/board_manager/board_manager.i"
	@echo "... src/board_manager/board_manager.s"
	@echo "... src/evaluate/evaluate.o"
	@echo "... src/evaluate/evaluate.i"
	@echo "... src/evaluate/evaluate.s"
	@echo "... src/lookup_tables/lookup_tables.o"
	@echo "... src/lookup_tables/lookup_tables.i"
	@echo "... src/lookup_tables/lookup_tables.s"
	@echo "... src/search/search.o"
	@echo "... src/search/search.i"
	@echo "... src/search/search.s"
	@echo "... tests/test_move_making.o"
	@echo "... tests/test_move_making.i"
	@echo "... tests/test_move_making.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

